dist: trusty
sudo: false
language: cpp

addons:
    apt:
        sources:
            - ubuntu-tool-chain-r-test
        packages:
            - g++-8-arm-linux-gnueabihf

script:
    - cmake -DCMAKE_TOOLCHAIN_FILE="cmake/Toolchain.cmake" .
    - cmake --build .
